export enum PlatformCapability {
  TREND_COLLECTION = 'TREND_COLLECTION',
  CONTENT_GENERATION = 'CONTENT_GENERATION',
  TEXT_PUBLISHING = 'TEXT_PUBLISHING',
  IMAGE_PUBLISHING = 'IMAGE_PUBLISHING',
  VIDEO_PUBLISHING = 'VIDEO_PUBLISHING',
  SCHEDULING = 'SCHEDULING',
  ANALYTICS = 'ANALYTICS',
  LINKS = 'LINKS',
  AUTHENTICATION = 'AUTHENTICATION'
}
