export enum PublishingStatus {
  DRAFT = 'DRAFT',
  READY = 'READY',
  WAITING_FOR_API = 'WAITING_FOR_API',
  MANUAL_PUBLISHING_REQUIRED = 'MANUAL_PUBLISHING_REQUIRED',
  COPIED = 'COPIED',
  DOWNLOADED = 'DOWNLOADED',
  PUBLISHED_MANUALLY = 'PUBLISHED_MANUALLY',
  PUBLISHED_AUTOMATICALLY = 'PUBLISHED_AUTOMATICALLY',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
  ARCHIVED = 'ARCHIVED'
}
