/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "375px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        background: "#131313",
        "on-background": "#e5e2e1",
        surface: "#131313",
        "on-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "on-surface-variant": "#c4c5da",
        primary: "#b9c3ff",
        "on-primary": "#001257",
        "primary-container": "#0047ff",
        "on-primary-container": "#d4d9ff",
        "primary-fixed": "#dde1ff",
        "on-primary-fixed": "#001257",
        "primary-fixed-dim": "#b9c3ff",
        "on-primary-fixed-variant": "#0033c0",
        secondary: "#ffdb9d",
        "on-secondary": "#412d00",
        "secondary-container": "#feb700",
        "on-secondary-container": "#6b4b00",
        "secondary-fixed": "#ffdea8",
        "on-secondary-fixed": "#271900",
        "secondary-fixed-dim": "#ffba20",
        "on-secondary-fixed-variant": "#5e4200",
        tertiary: "#e9c349",
        "on-tertiary": "#3c2f00",
        "tertiary-container": "#cba72f",
        "on-tertiary-container": "#4e3d00",
        "tertiary-fixed": "#ffe088",
        "on-tertiary-fixed": "#241a00",
        "tertiary-fixed-dim": "#e9c349",
        "on-tertiary-fixed-variant": "#574500",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "outline": "#8e8fa3",
        "outline-variant": "#434657",
        "inverse-surface": "#e5e2e1",
        "inverse-primary": "#0046fa",
        "on-inverse-surface": "#313030",
        "deep-navy": "#00113A",
        "electric-indigo": "#0047FF",
        "gold-leaf": "#D4AF37",
        "brand-teal": "#0F766E",
        "brand-teal-dark": "#064E3B",
        "brand-mint": "#D1FAE5",
        "brand-green": "#22C55E",
        "obsidian": "#0A0A0A",
        "obsidian-deep": "#0A0A0A",
        "charcoal-surface": "#131313",
        "paper-white": "#F9F9F9",
        "slate-border": "#2E2E2E",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "max-content-width": "1280px",
        gutter: "24px",
        base: "8px",
      },
      fontFamily: {
        "headline-xl": ["'Playfair Display'", "serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "headline-lg-mobile": ["'Playfair Display'", "serif"],
        "label-caps": ["'Geist'", "sans-serif"],
        "mono-data": ["'Geist'", "sans-serif"],
        "ui-body": ["'Inter'", "sans-serif"],
        "editorial-body": ["'Inter'", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-data": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "500" }],
        "ui-body": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "editorial-body": ["18px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "400" }],
      },
      animation: {
        shimmer: "shimmer 1.5s infinite",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
}
