/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "375px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        // ── Editorial Canvas: deep near-black ──
        primary: "#131313",
        "on-primary": "#f5f5f5",
        "primary-container": "#1e1e1e",
        "on-primary-container": "#e0e0e0",
        secondary: "#8a8a8a",
        "on-secondary": "#ffffff",
        "secondary-container": "#2d2d2d",
        "on-secondary-container": "#b0b0b0",
        tertiary: "#3cffd0",
        "on-tertiary": "#131313",
        "tertiary-container": "#1a3a35",
        "on-tertiary-container": "#3cffd0",
        // ── Background: near-black editorial canvas ──
        background: "#131313",
        "on-background": "#f5f5f5",
        surface: "#131313",
        "on-surface": "#f5f5f5",
        "surface-container-low": "#181818",
        "surface-container-lowest": "#0d0d0d",
        "surface-container": "#1e1e1e",
        "surface-container-high": "#252525",
        "surface-container-highest": "#2d2d2d",
        "surface-variant": "#2d2d2d",
        "on-surface-variant": "#b0b0b0",
        // ── Accent: neon hazard colors for focal items ──
        "gold-accent": "#3cffd0",
        "neon-accent": "#5200ff",
        "hazard-green": "#3cffd0",
        "hazard-purple": "#5200ff",
        outline: "#2d2d2d",
        "outline-variant": "#1e1e1e",
        error: "#ff4444",
        "on-error": "#ffffff",
        "error-container": "#2a1111",
        "on-error-container": "#ff6b6b",
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1440px",
        unit: "8px",
        gutter: "24px",
        "section-gap": "80px",
      },
      fontFamily: {
        display: ["'Playfair Display'", "serif"],
        body: ["'Inter'", "sans-serif"],
        mono: ["'JetBrains Mono'", "'Courier New'", "monospace"],
      },
      fontSize: {
        "editorial-xl": ["4.5rem", { lineHeight: "1.0", letterSpacing: "-0.04em" }],
        "editorial-lg": ["3.5rem", { lineHeight: "1.05", letterSpacing: "-0.03em" }],
        "editorial-md": ["2.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
        "editorial-sm": ["1.75rem", { lineHeight: "1.2", letterSpacing: "-0.01em" }],
      },
      animation: {
        shimmer: "shimmer 1.5s infinite",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
}
