import { AIProviderType, AIProviderConfig } from '../core/ai/types';

export const defaultProviderConfigs: Record<AIProviderType, AIProviderConfig> = {
  // Text AI
  [AIProviderType.OLLAMA]: {
    baseUrl: process.env.OLLAMA_BASE_URL || 'http://localhost:11434',
    defaultModel: process.env.OLLAMA_DEFAULT_MODEL || 'llama3:latest',
    timeoutMs: 60000,
    maxRetries: 3,
    disabled: process.env.OLLAMA_DISABLED === 'true',
  },
  [AIProviderType.GEMINI]: {
    apiKey: process.env.GEMINI_API_KEY,
    defaultModel: process.env.GEMINI_MODEL || 'gemini-3.6-flash',
    timeoutMs: parseInt(process.env.GEMINI_TIMEOUT_MS || '120000', 10),
    maxRetries: parseInt(process.env.GEMINI_MAX_RETRIES || '2', 10),
    disabled: process.env.GEMINI_DISABLED === 'true',
  },
  [AIProviderType.OPENAI]: {
    apiKey: process.env.OPENAI_API_KEY,
    defaultModel: process.env.OPENAI_MODEL || 'gpt-4o',
    timeoutMs: parseInt(process.env.OPENAI_TIMEOUT_MS || '120000', 10),
    maxRetries: parseInt(process.env.OPENAI_MAX_RETRIES || '2', 10),
    disabled: process.env.OPENAI_DISABLED === 'true',
  },
  [AIProviderType.CLAUDE]: {
    apiKey: process.env.ANTHROPIC_API_KEY,
    defaultModel: process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-20250514',
    timeoutMs: parseInt(process.env.ANTHROPIC_TIMEOUT_MS || '120000', 10),
    maxRetries: parseInt(process.env.ANTHROPIC_MAX_RETRIES || '2', 10),
    disabled: process.env.CLAUDE_DISABLED === 'true' || process.env.ANTHROPIC_DISABLED === 'true',
  },
  [AIProviderType.OPENROUTER]: {
    apiKey: process.env.OPENROUTER_API_KEY,
    defaultModel: process.env.OPENROUTER_MODEL || 'meta-llama/llama-3.3-70b-instruct',
    timeoutMs: parseInt(process.env.OPENROUTER_TIMEOUT_MS || '120000', 10),
    maxRetries: parseInt(process.env.OPENROUTER_MAX_RETRIES || '2', 10),
    disabled: process.env.OPENROUTER_DISABLED === 'true',
  },
  [AIProviderType.GROQ]: {
    apiKey: process.env.GROQ_API_KEY,
    defaultModel: process.env.GROQ_MODEL || 'llama-3.3-70b-versatile',
    timeoutMs: parseInt(process.env.GROQ_TIMEOUT_MS || '120000', 10),
    maxRetries: parseInt(process.env.GROQ_MAX_RETRIES || '2', 10),
    disabled: process.env.GROQ_DISABLED === 'true',
  },
  [AIProviderType.DEEPSEEK]: {
    apiKey: process.env.DEEPSEEK_API_KEY,
    defaultModel: process.env.DEEPSEEK_MODEL || 'deepseek-chat',
    timeoutMs: parseInt(process.env.DEEPSEEK_TIMEOUT_MS || '120000', 10),
    maxRetries: parseInt(process.env.DEEPSEEK_MAX_RETRIES || '2', 10),
    disabled: process.env.DEEPSEEK_DISABLED === 'true',
  },
  [AIProviderType.MISTRAL]: {
    apiKey: process.env.MISTRAL_API_KEY,
    defaultModel: process.env.MISTRAL_MODEL || 'mistral-small-latest',
    timeoutMs: parseInt(process.env.MISTRAL_TIMEOUT_MS || '120000', 10),
    maxRetries: parseInt(process.env.MISTRAL_MAX_RETRIES || '2', 10),
    disabled: process.env.MISTRAL_DISABLED === 'true',
  },

  // Image AI
  [AIProviderType.GOOGLE_IMAGEN]: {
    apiKey: process.env.GOOGLE_IMAGEN_API_KEY,
    defaultModel: 'imagen-3.0-generate-002',
    timeoutMs: 30000,
    maxRetries: 2,
    disabled: process.env.GOOGLE_IMAGEN_DISABLED === 'true',
  },
  [AIProviderType.BFL]: {
    apiKey: process.env.BFL_API_KEY,
    defaultModel: 'flux-1-schnell',
    timeoutMs: 30000,
    maxRetries: 2,
    disabled: process.env.BFL_DISABLED === 'true',
  },
  [AIProviderType.IDEOGRAM]: {
    apiKey: process.env.IDEOGRAM_API_KEY,
    defaultModel: 'ideogram-2.0',
    timeoutMs: 30000,
    maxRetries: 2,
    disabled: process.env.IDEOGRAM_DISABLED === 'true',
  },
  [AIProviderType.LEONARDO]: {
    apiKey: process.env.LEONARDO_API_KEY,
    defaultModel: 'leonardo-creative-v2',
    timeoutMs: 30000,
    maxRetries: 2,
    disabled: process.env.LEONARDO_DISABLED === 'true',
  },
  [AIProviderType.FAL]: {
    apiKey: process.env.FAL_KEY || process.env.FAL_API_KEY,
    defaultModel: 'fal-flux-schnell',
    timeoutMs: 30000,
    maxRetries: 2,
    disabled: process.env.FAL_DISABLED === 'true',
  },
  [AIProviderType.REPLICATE]: {
    apiKey: process.env.REPLICATE_API_TOKEN,
    defaultModel: 'stability-ai/sdxl',
    timeoutMs: 30000,
    maxRetries: 2,
    disabled: process.env.REPLICATE_DISABLED === 'true',
  },
  [AIProviderType.STABILITY_AI]: {
    apiKey: process.env.STABILITY_API_KEY,
    defaultModel: 'stable-diffusion-xl-1024-v1-0',
    timeoutMs: 30000,
    maxRetries: 2,
    disabled: process.env.STABILITY_AI_DISABLED === 'true',
  },

  // Video AI
  [AIProviderType.GOOGLE_VEO]: {
    apiKey: process.env.GOOGLE_VEO_API_KEY,
    defaultModel: 'veo-2.0',
    timeoutMs: 60000,
    maxRetries: 2,
    disabled: process.env.GOOGLE_VEO_DISABLED === 'true',
  },
  [AIProviderType.RUNWAY]: {
    apiKey: process.env.RUNWAY_API_KEY,
    defaultModel: 'runway-gen3',
    timeoutMs: 60000,
    maxRetries: 2,
    disabled: process.env.RUNWAY_DISABLED === 'true',
  },
  [AIProviderType.KLING]: {
    apiKey: process.env.KLING_API_KEY,
    defaultModel: 'kling-1.5',
    timeoutMs: 60000,
    maxRetries: 2,
    disabled: process.env.KLING_DISABLED === 'true',
  },
  [AIProviderType.PIKA]: {
    apiKey: process.env.PIKA_API_KEY,
    defaultModel: 'pika-1.0',
    timeoutMs: 60000,
    maxRetries: 2,
    disabled: process.env.PIKA_DISABLED === 'true',
  },
  [AIProviderType.LUMA]: {
    apiKey: process.env.LUMA_API_KEY,
    defaultModel: 'luma-dream-machine',
    timeoutMs: 60000,
    maxRetries: 2,
    disabled: process.env.LUMA_DISABLED === 'true',
  },
  [AIProviderType.HAIPER]: {
    apiKey: process.env.HAIPER_API_KEY,
    defaultModel: 'haiper-1.5',
    timeoutMs: 60000,
    maxRetries: 2,
    disabled: process.env.HAIPER_DISABLED === 'true',
  },
  [AIProviderType.FAL_VIDEO]: {
    apiKey: process.env.FAL_VIDEO_API_KEY,
    defaultModel: 'fal-video-gen',
    timeoutMs: 60000,
    maxRetries: 2,
    disabled: process.env.FAL_VIDEO_DISABLED === 'true',
  },
  [AIProviderType.REPLICATE_VIDEO]: {
    apiKey: process.env.REPLICATE_VIDEO_TOKEN,
    defaultModel: 'replicate-video-gen',
    timeoutMs: 60000,
    maxRetries: 2,
    disabled: process.env.REPLICATE_VIDEO_DISABLED === 'true',
  },
};
