export const DIGITAL_PRODUCTS_NICHE = {
  name: 'Digital Products Editorial',
  description: 'Editorial content about software, SaaS, AI tools, productivity tools, and digital services.',
  allowedCategories: [
    'ai-tools',
    'saas',
    'software',
    'productivity',
    'developer-tools',
    'design-tools',
    'marketing-tools',
    'creator-tools',
    'business-software',
    'online-platforms',
    'digital-services',
    'automation-tools',
    'analytics-tools',
    'collaboration-tools',
    'security-tools',
    'cloud-services',
    'api-services',
    'no-code-tools',
    'low-code-tools',
    'data-tools',
  ],
  excludedCategories: [
    'physical-products',
    'beauty',
    'fashion',
    'collectibles',
    'home-garden',
    'sports',
    'automotive',
    'health-physical',
    'travel-physical',
    'food-physical',
    'gaming-physical',
  ],
  contentTypes: [
    'article',
    'guide',
    'tutorial',
    'comparison',
    'review',
    'blog',
  ],
  topicRules: {
    mustBeDigital: true,
    mustBeSoftwareOrService: true,
    noPhysicalProducts: true,
    noCollectibles: true,
    noBeautyProducts: true,
    noFashionProducts: true,
    minRelevanceScore: 0.7,
  },
  researchRules: {
    sources: [
      'official-documentation',
      'product-websites',
      'developer-communities',
      'review-sites',
      'social-proof',
      'pricing-pages',
    ],
    excludedSources: [
      'physical-retailers',
      'general-marketplaces',
      'unrelated-blogs',
    ],
    requireFactualVerification: true,
    maxClaimsWithoutSource: 2,
  },
  contentRules: {
    minWordCount: 800,
    maxWordCount: 5000,
    requireHeadingStructure: true,
    requireMetaDescription: true,
    requireFeaturedImage: true,
    requireAuthorAttribution: true,
    requireDisclosure: true,
    allowAffiliateLinks: true,
    requireTransparentAffiliateDisclosure: true,
  },
  affiliateRules: {
    requireDisclosure: true,
    discloseInContent: true,
    discloseInFooter: true,
    noHiddenLinks: true,
    noDeceptivePlacement: true,
    maxAffiliateDensity: 0.15,
  },
  seoRules: {
    requireTitleTag: true,
    requireMetaDescription: true,
    requireHeadingHierarchy: true,
    requireInternalLinks: true,
    requireImageAltText: true,
    requireCanonicalUrl: true,
    requireStructuredData: true,
    minTitleLength: 30,
    maxTitleLength: 70,
    minMetaDescriptionLength: 120,
    maxMetaDescriptionLength: 160,
  },
  geoRules: {
    requireDirectAnswer: true,
    requireEntityClarity: true,
    requireFactualAccuracy: true,
    requireSourceAttribution: true,
    maxUnverifiedClaims: 0,
  },
  aeoRules: {
    requireQuestionCoverage: true,
    requireConciseAnswers: true,
    requireFAQOpportunities: true,
    requireHeadingAsQuestion: true,
    requireStructuredData: true,
    requireSourceQuality: 'high',
  },
} as const

export type NicheConfig = typeof DIGITAL_PRODUCTS_NICHE
