import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { workflowRegistry } from '../workflows/core/WorkflowRegistry';
import { WorkflowType } from '../workflows/core/types';
import { createClient } from '@sanity/client';
import { agentRegistry } from '../agents/core/AgentRegistry';

// Mock AIManager to skip real AI call
const { aiManager } = require('../core/ai/AIManager');
aiManager.execute = async (promptId: string, variables: any) => {
  console.log('MOCK AI MANAGER CALLED with URL:', variables.url);
  return {
    content: JSON.stringify({
      title: variables.title || "Mock Product",
      brand: variables.brand || "Mock Brand",
      price: variables.price || 99.99,
      description: "Mock Description generated by AI",
      category: "Electronics", // This should resolve to the Electronics category if it exists
      subcategory: "Collectibles",
      bestCategory: "Action Figures",
      merchant: "Amazon",
      affiliateNetwork: "Amazon",
      slug: "mock-product-slug"
    })
  };
};

// Bootstrap
import { ProviderLoader } from '../providers/ProviderLoader';
import { AgentLoader } from '../agents/core/AgentLoader';
import { WorkflowLoader } from '../workflows/core/WorkflowLoader';

async function runTest() {
  await ProviderLoader.loadProviders();
  await AgentLoader.loadAgents();
  await WorkflowLoader.loadWorkflows();

  const testUrl = 'https://www.amazon.com/dp/B0DJYC3WDN';
  const workflow = workflowRegistry.getWorkflow(WorkflowType.PRODUCT);
  
  console.log(`Starting mock pipeline test for ${testUrl}...`);
  const result = await workflow!.run({
    workflowId: `mockrun-${Date.now()}`,
    type: WorkflowType.PRODUCT,
    triggeredBy: 'manual',
    timestamp: new Date().toISOString(),
    payload: { productUrl: testUrl }
  });

  if (result.errors.length > 0) {
    console.error("Pipeline Errors:", result.errors);
  } else {
    console.log("Pipeline Success!");
    console.log("Sanity Doc Draft ID:", result.data?.sanityDoc?._id);
    console.log("Resolved Category Ref:", result.data?.sanityDoc?.suggestedCategory);
    console.log("Resolved Brand Ref:", result.data?.sanityDoc?.brand);
  }
  process.exit(0);
}

runTest().catch(console.error);
