// 61-article forensic audit: classify REAL / TEST / UNKNOWN by content (no secrets)
const { Pool } = require('pg');
require('dotenv').config({ path: '.env.local' });
const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 5 });

function classify(row) {
  const text = ((row.title || '') + ' ' + (row.content || '')).toLowerCase();
  const signals = {
    test: ['lorem ipsum', 'placeholder text', 'this is a test', 'test article', 'demo article',
           'sample article', 'auto-generated test', 'mock content', 'test content', 'fixture',
           'dummy content', 'viafinds test', 'test placeholder', 'generated by test'],
    real: ['affiliate', 'commission', 'digistore', 'payout', 'conversion', 'revenue',
           'digital product', 'saas', 'course', 'ebook', 'review', 'buy now', 'checkout',
           'discount', 'offer', 'deal', 'recommended', 'best ', 'top ', 'vs ', 'comparison'],
  };
  let testScore = signals.test.filter(s => text.includes(s)).length;
  let realScore = signals.real.filter(s => text.includes(s)).length;
  let verdict;
  if (testScore > 0 && realScore === 0) verdict = 'TEST';
  else if (realScore > 0 && testScore === 0) verdict = 'REAL';
  else if (testScore > 0) verdict = 'TEST (test signals present, but some real content)';
  else verdict = 'UNKNOWN';
  return { verdict, testScore, realScore };
}

async function main() {
  const r = await pool.query(`
    SELECT id, title, slug, status, provenance, created_at, published_at,
           product_id, affiliate_url, content
    FROM articles ORDER BY created_at DESC
  `);
  console.log('Total articles: ' + r.rows.length);
  const counts = {};
  r.rows.forEach(row => {
    const c = classify(row);
    row._class = c.verdict;
    counts[c.verdict] = (counts[c.verdict] || 0) + 1;
  });
  console.log('\n=== Classification counts ===');
  console.log(JSON.stringify(counts, null, 2));
  console.log('\n=== Per-article classification ===');
  r.rows.forEach(row => {
    console.log(JSON.stringify({
      id: row.id, title: (row.title || '').slice(0, 50), slug: (row.slug || '').slice(0, 40),
      status: row.status, provenance: row.provenance, created_at: row.created_at,
      published_at: row.published_at, product_id: row.product_id, class: row._class,
      content: (row.content || '').slice(0, 90),
    }));
  });
  await pool.end();
}
main().catch(e => { console.error(e.message); process.exit(1); });