// Summarize article classification counts from audit
const { Pool } = require('pg');
require('dotenv').config({ path: '.env.local' });
const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 5 });

function classify(row) {
  const text = ((row.title || '') + ' ' + (row.content || '')).toLowerCase();
  const signals = {
    test: ['lorem ipsum', 'placeholder text', 'this is a test', 'test article', 'demo article',
           'sample article', 'auto-generated test', 'mock content', 'test content', 'fixture',
           'dummy content', 'viafinds test', 'test placeholder', 'generated by test'],
    real: ['affiliate', 'commission', 'digistore', 'payout', 'conversion', 'revenue',
           'digital product', 'saas', 'course', 'ebook', 'review', 'buy now', 'checkout',
           'discount', 'offer', 'deal', 'recommended', 'best ', 'top ', 'vs ', 'comparison'],
  };
  let testScore = signals.test.filter(s => text.includes(s)).length;
  let realScore = signals.real.filter(s => text.includes(s)).length;
  if (testScore > 0 && realScore === 0) return 'TEST';
  if (realScore > 0 && testScore === 0) return 'REAL';
  if (testScore > 0) return 'TEST (mixed)';
  return 'UNKNOWN';
}

async function main() {
  const r = await pool.query('SELECT id, title, slug, status, provenance, published_at, product_id, content FROM articles ORDER BY created_at DESC');
  const counts = { REAL: 0, TEST: 0, 'TEST (mixed)': 0, UNKNOWN: 0 };
  r.rows.forEach(row => { counts[classify(row)]++; });
  console.log('\n=== CLASSIFICATION COUNTS ===');
  console.log(JSON.stringify(counts, null, 2));
  console.log('Total: ' + r.rows.length);
  console.log('\n=== REAL articles ===');
  r.rows.forEach(row => { if (classify(row) === 'REAL') console.log(JSON.stringify({ title: row.title, slug: row.slug, status: row.status, provenance: row.provenance, published_at: row.published_at, product_id: row.product_id })); });
  console.log('\n=== TEST articles ===');
  r.rows.forEach(row => { if (classify(row) === 'TEST' || classify(row) === 'TEST (mixed)') console.log(JSON.stringify({ title: row.title, slug: row.slug, status: row.status, provenance: row.provenance, published_at: row.published_at })); });
  await pool.end();
}
main().catch(e => { console.error(e.message); process.exit(1); });