import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'tool',
  title: 'Tools',
  type: 'document',
  icon: () => '🔧',
  fields: [
    defineField({
      name: 'title',
      title: 'Tool Title',
      type: 'string',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'toolType',
      title: 'Tool Type',
      type: 'string',
      description: 'Used to render the correct calculator component.',
      options: {
        list: [
          { title: 'Discount Calculator', value: 'discount' },
          { title: 'Scale Converter', value: 'scale' },
          { title: 'Currency Converter', value: 'currency' },
          { title: 'Reading Time', value: 'reading-time' },
          { title: 'Percentage Calculator', value: 'percentage' },
          { title: 'BMI Calculator', value: 'bmi' },
          { title: 'Age Calculator', value: 'age' },
          { title: 'QR Code Generator', value: 'qr' },
          { title: 'Password Generator', value: 'password' },
          { title: 'Unit Converter', value: 'unit' },
          { title: 'Color Converter', value: 'color' },
          { title: 'Tax Calculator', value: 'tax' },
          { title: 'Tip Calculator', value: 'tip' },
          { title: 'Storage Converter', value: 'storage' },
          { title: 'Speed Converter', value: 'speed' },
          { title: 'Custom / External', value: 'custom' },
        ],
      },
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'array',
      of: [{ type: 'block' }],
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
      rows: 2,
      description: 'Shown on the toolkit grid card.',
    }),
    defineField({
      name: 'icon',
      title: 'Icon (Material Symbol)',
      type: 'string',
      description: 'e.g. payments, palette, speed, qr_code_2',
    }),
    defineField({
      name: 'route',
      title: 'Route / Hash (Legacy)',
      type: 'string',
      description: 'Legacy hash route. Use Slug instead for new tools.',
      hidden: true,
    }),
    defineField({
      name: 'buttonLabel',
      title: 'Button Label',
      type: 'string',
      initialValue: 'Launch Tool',
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'order',
      title: 'Display Order',
      type: 'number',
      description: 'Lower numbers appear first.',
      initialValue: 0,
    }),
    defineField({
      name: 'relatedArticles',
      title: 'Related Articles',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'article' }] }],
    }),
    defineField({
      name: 'relatedProducts',
      title: 'Related Products',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'product' }] }],
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
    }),
    defineField({
      name: 'affiliateUrl',
      title: 'Affiliate URL',
      type: 'url',
      description: 'Link to affiliate landing page if the tool redirects externally.',
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Tags for organizing tools.',
    }),
  ],
  orderings: [
    { title: 'Display Order', name: 'orderAsc', by: [{ field: 'order', direction: 'asc' }] },
    { title: 'Title A–Z', name: 'titleAsc', by: [{ field: 'title', direction: 'asc' }] },
  ],
  preview: {
    select: { title: 'title', subtitle: 'toolType' },
  },
})
